server: 
   port: 9999
   
spring: 
   application: 
      name: fresh-zuul 
eureka: 
   client: 
      service-url: 
         defaultZone: http://zzm:123456@127.0.0.1:6868/eureka
                  
zuul: 
   max: 
      host: 
         connections: 500
   host: 
      maxTotalConnections: 200   # 最大连接数  默认200
      maxPerRouteConnections: 20
      socket-timeout-millis: 60000
      connect-timeout-millis: 60000
   routes: 
      #
      service-rpc-user: 
         #
         path: /user/**
         serviceId: fresh-user
         
      service-rpc-goods: 
         #
         path: /view/**
         serviceId: fresh-goods
         
      service-rpc-order: 
         #
         path: /order/**
         serviceId: fresh-order